name: AppFlutter

on:
  push:
    branches: ["develop"]
  workflow_dispatch:

jobs:
  Teste:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Teste com SonarQube
      run: echo "Aqui irá as intruções do teste do código"

  Build:
    needs: Teste
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: "12.x"

    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        channel: "stable"

    - name: Install dependencies
      run: flutter pub get

    - name: Build Web
      id: build_web
      run: flutter build web
      continue-on-error: true

    - name: Build Android
      id: build_android
      run: |
        flutter analyze .
        flutter build apk
    - uses: actions/upload-artifact@v1
      with:
        name: release-apk
        path: build/app/outputs/apk/release/app-release.apk
        #mv build/app/outputs/flutter-apk/app-release.apk ${{ github.workspace }}/app-release.apk
      continue-on-error: true

  Notification:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Notify Success
      if: success() && needs.build.result == 'success' && needs.build.outputs.build_android == 'success' || needs.build.outputs.build_web == 'success'
      run: sh ./.scripts/notificationSuccess.sh

    - name: Notify Failure
      if: failure() && (needs.build.result == 'failure' || needs.build.outputs.build_android == 'failure' || needs.build.outputs.build_web == 'failure')
      run: sh ./.scripts/notificationFailure.sh

  Deploy:
    needs: Notification
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup SendEmail
      run: sudo apt install sendemail openssl perl libio-socket-inet6-perl libio-socket-ssl-perl libnet-ssleay-perl

    - name: Send Email add .apk
      run: sh ./.scripts/sendMail.sh



