name: AppFlutter

on:
  push:
    branches: ["develop"]
  workflow_dispatch:

jobs:
  Teste:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Teste com SonarQube
      run: echo "Aqui irá as intruções do teste do código"

  Build:
    needs: Teste
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        channel: "stable"

    - name: Install dependencies
      run: flutter pub get

    - name: Build Web
      run: flutter build web

    - name: Build Android
      run: echo "Aqui vão as instrução do .apk depois dos testes"

  Notification:
    needs: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Successo
      uses: workflow/nix-shell-action@v3.3.0
      with:
        interpreter: bash
        context: ./autoleitura/.scripts
        file: .scripts/notificationSuccess.sh
        if: ${{ success() }}
        run: notificationSucess.sh

    - name: Falha
      uses: workflow/nix-shell-action@v3.3.0
      with:
        interpreter: bash
        context: ./autoleitura/.scripts
        file: .scripts/notificationFailure.sh
        if: ${{ failure() }}
        run: notificationFailure.sh



  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Instalar SendEmail
      run: sudo apt install sendemail
