name: AppFlutter

on:
  push:
    branches: ["develop"]
  workflow_dispatch:

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        channel: "stable"

    - name: Install dependencies
      run: flutter pub get

    - name: Build Web
      run: flutter build web

    - name: Notification
      run: curl -X POST "https://api.telegram.org/bot5352882450:AAElAs4XYp0r5gYHoWrovu7-WLYcKjSb2Qk/sendMessage" -d "chat_id=-783035082&text=Pipeline Executada com FALHAS"



