name: AppFlutter

on:
  push:
    branches: ["develop"]
  workflow_dispatch:
    
jobs:
  web:
    runs-on: ubuntu-latest
    steps:
    - name: Install Flutter
      #uses: steebchen/flutter@v1.1.0
      uses: britannio/action-install-flutter@v1.1
      
     
      
