name: AppFlutter

on:
  push:
    branches: ["develop"]
  workflow_dispatch:

jobs:
  Teste:
    runs-on: ubuntu-latest
    steps:
    - name: Teste com SonarQube
      run: echo "Aqui irá as intruções do teste do código"

  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        channel: "stable"

    - name: Install dependencies
      run: flutter pub get

    - name: Build Web
      run: flutter build web

    - name: Build Android
      run: echo "Aqui vão as instrução do .apk depois dos testes"

    - name: Notification
      if: ${{ failure() }}
      run: |
        curl -X POST "https://api.telegram.org/bot5352882450:AAElAs4XYp0r5gYHoWrovu7-WLYcKjSb2Qk/sendMessage" -d "chat_id=-783035082&text=Pipeline Executada com FALHAS"

  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    steps:
    - name: Instalar SendEmail
      run: "\"echo \"Instalado o sendemail para enviar o .apk para testadores\"     \nsudo apt install sendemail\n"
