name: AppFlutter

on:
  push:
    branches: ["develop"]
  workflow_dispatch:
    
jobs:
  web:
    runs-on: ubuntu-latest
    steps:
    - name: Flutter Build
      uses: jeanluc243/Flutter-Deployment@0.1
      with:
        version: 3.13.0
        context: .
        file: pubspec.yaml
      #run: flutter build web 
     
      
